export const ERROR_CODES = {
  // Auth: 001-099
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_EMAIL_EXISTS: 'AUTH_002',
  AUTH_PHONE_EXISTS: 'AUTH_003',
  AUTH_TOKEN_EXPIRED: 'AUTH_004',
  AUTH_TOKEN_INVALID: 'AUTH_005',
  AUTH_TOKEN_REVOKED: 'AUTH_006',
  AUTH_OTP_EXPIRED: 'AUTH_007',
  AUTH_OTP_INVALID: 'AUTH_008',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_009',
  AUTH_OTP_RATE_LIMITED: 'AUTH_010',
  AUTH_FORBIDDEN: 'AUTH_011',
  AUTH_MISSING_IDENTIFIER: 'AUTH_012',

  // Order: 100-199
  ORDER_NOT_FOUND: 'ORDER_100',
  ORDER_INVALID_TRANSITION: 'ORDER_101',
  ORDER_ALREADY_CANCELLED: 'ORDER_102',
  ORDER_NOT_OWNED: 'ORDER_103',
  ORDER_ALREADY_RATED: 'ORDER_104',
  ORDER_NOT_COMPLETED: 'ORDER_105',
  ORDER_INVALID_SERVICE_DETAILS: 'ORDER_106',

  // Negotiation: 200-299
  NEG_ORDER_NOT_NEGOTIATING: 'NEG_200',
  NEG_OFFER_NOT_FOUND: 'NEG_201',
  NEG_OFFER_EXPIRED: 'NEG_202',
  NEG_OFFER_ALREADY_ACCEPTED: 'NEG_203',
  NEG_AMOUNT_OUT_OF_BOUNDS: 'NEG_204',
  NEG_AMOUNT_BAD_INCREMENT: 'NEG_205',
  NEG_MESSAGE_TOO_LONG: 'NEG_206',
  NEG_DUPLICATE_MESSAGE: 'NEG_207',

  // Pro: 300-399
  PRO_NOT_FOUND: 'PRO_300',
  PRO_NOT_AVAILABLE: 'PRO_301',
  PRO_ASSIGNMENT_NOT_FOUND: 'PRO_302',
  PRO_ASSIGNMENT_WRONG_STATUS: 'PRO_303',
  PRO_NOT_ASSIGNED: 'PRO_304',
  PRO_NOT_LEAD: 'PRO_305',
  PRO_ALREADY_JOINED: 'PRO_306',
  PRO_NO_OPEN_SLOTS: 'PRO_307',

  // Admin: 400-499
  ADMIN_USER_NOT_FOUND: 'ADMIN_400',

  // General: 900-999
  VALIDATION_ERROR: 'GEN_900',
  NOT_FOUND: 'GEN_901',
  INTERNAL_ERROR: 'GEN_999',
  RATE_LIMITED: 'GEN_902',
  IDEMPOTENCY_CONFLICT: 'GEN_903',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
